name: YouTube Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
    - cron: "0 9 * * *"
    - cron: "0 14 * * *"

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Create video
        run: python main.py

      - name: Upload generated video
        uses: actions/upload-artifact@v4
        with:
          name: generated-video
          path: output.mp4
